# Generated by Django 4.0.4 on 2022-05-04 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E nevojshme', max_length=255, unique=True, verbose_name='Emri')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Qyteti',
                'verbose_name_plural': 'Qytetet',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E nevojshme', max_length=255, unique=True, verbose_name='Emri')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.city')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonat',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.TextField(help_text='Vendos titullin e njoftimit', max_length=500, verbose_name='Titulli')),
                ('description', models.TextField(help_text='Vendos pershkrimin', max_length=1000, verbose_name='Pershkrimi')),
                ('address_line', models.CharField(help_text='E nevojeshme', max_length=255, verbose_name='Adresa')),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
                ('documents', models.CharField(help_text='Dokumentat', max_length=255, verbose_name='Dokumentacioni')),
                ('status', models.BooleanField(default=True)),
                ('activity', models.CharField(choices=[('Sale', 'Shitje'), ('Rent', 'Qera')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_creator', to=settings.AUTH_USER_MODEL)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.district')),
            ],
            options={
                'verbose_name': 'Prona',
                'verbose_name_plural': 'Pronat',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
                ('floor', models.IntegerField(default=0)),
                ('room_num', models.IntegerField(default=0)),
                ('bath_num', models.IntegerField(default=0)),
                ('balcony_num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Apartament',
                'verbose_name_plural': 'Apartamentet',
            },
            bases=('property.property',),
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
                ('floor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Garazhd',
                'verbose_name_plural': 'Garazhdet',
            },
            bases=('property.property',),
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
            ],
            options={
                'verbose_name': 'Toke',
                'verbose_name_plural': 'Tokat',
            },
            bases=('property.property',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
                ('floor', models.IntegerField(default=-1)),
                ('bath_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dyqan',
                'verbose_name_plural': 'Dyqanet',
            },
            bases=('property.property',),
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('property_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='property.property')),
                ('floors', models.IntegerField(default=1)),
                ('room_num', models.IntegerField(default=1)),
                ('bath_num', models.IntegerField(default=1)),
                ('balcony_num', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vila',
                'verbose_name_plural': 'Vilat',
            },
            bases=('property.property',),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a property image', upload_to='images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Please add alturnative text', max_length=255, null=True, verbose_name='Alturnative text')),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_image', to='property.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
            },
        ),
    ]
